### ISSUE TITLE
RSS news feeds crash when loading older entries

### ISSUE THREAD

**Issue by TonEnsing** [shoutem/extensions#5]
RSS news feeds crash when loading older entries. Both on the device and in the Shoutem builder preview. Don't know if its an extension related bug or a preview bug.

![screen shot 2017-04-14 at 09 37 28](https://cloud.githubusercontent.com/assets/557107/25040095/ac238ad0-2107-11e7-921e-823b1d3ed8de.png)
.

**Comment by tenodi** [comment]
Hi @TonEnsing! Did you update the Shoutem platform?

**Comment by TonEnsing** [comment]
Hi @tenodi Yup, I did. Refreshing works fine now. Thanks.
